LUAZ
LUAZ_Doors_Driver
LUAZ_Doors_coDriver
LUAZ_Doors_hood
LUAZ_Doors_trunk
LUAZ_tent

HatchbackWheel

LUAZ_black
LUAZ_Doors_Driver_black
LUAZ_Doors_coDriver_black
LUAZ_Doors_hood_black
LUAZ_Doors_trunk_black
LUAZ_tent_black

LUAZ_red
LUAZ_Doors_Driver_red
LUAZ_Doors_coDriver_red
LUAZ_Doors_hood_red
LUAZ_Doors_trunk_red
LUAZ_tent_red

LUAZ_blue
LUAZ_Doors_Driver_blue
LUAZ_Doors_coDriver_blue
LUAZ_Doors_hood_blue
LUAZ_Doors_trunk_blue
LUAZ_tent_blue

LUAZ_rust
LUAZ_Doors_Driver_rust
LUAZ_Doors_coDriver_rust
LUAZ_Doors_hood_rust
LUAZ_Doors_trunk_rust
LUAZ_tent_rust